### Create a new report
POST http://localhost:3010/reports
Content-Type: application/json

{
    "data": {
    "roadType": "Bridge",
    },
    "userId": "019652b5-4e6f-74dc-8344-d43a581c2111"
}

### Get all reports
GET http://localhost:3010/reports
Content-Type: application/json

### Get a single report by ID
GET http://localhost:3010/reports/01942191-72a6-763c-ace3-66c84bc7f5ff
Content-Type: application/json

### Get all reports with incidents
GET http://localhost:3010/reports/incidents
Content-Type: application/json

### Update a report by ID
PUT http://localhost:3010/reports/01942191-72a6-763c-ace3-66c84bc7f5ff
Content-Type: application/json

{
    "description": "Updated report description..",
    "localisation": "Updated NGOA",
    "category": "accident",
    "latitude": 1.2345,
    "longitude": 1.2345,
    "photos": [
        {
            "url": "http://example.com/photo1.jpg",
            "type": "image"
        }
    ],
    "roadType": "highway",
    "userId": "01940bbb-6866-7709-9fe8-d2ef857c65b7"
}

### Delete a report by ID
DELETE http://localhost:3010/reports/1
Content-Type: application/json
