### Get all users
GET http://localhost:3010/users
Content-Type: application/json

###

### Get a single user by ID
GET  http://localhost:3010/users/0194036f-65c8-72a0-bd95-b56b1989444a
Content-Type: application/json

###

### Create a new user
POST http://localhost:3010/users/register
Content-Type: application/json

{
    "username": "Abba Sali Aboubakar Mamate",
    "email": "abbasaliaboubakar@gmail.com",
    "password": "password123",
    "localisation": "fr"
}

### Login a new user
POST http://localhost:3010/users/login
Content-Type: application/json

{
    "email": "abbasaliaboubakar@gmail.com",
    "password": "password123"
}
###

### Verify a user
POST  http://localhost:3010/users/verify/01946483-6860-77fd-b53c-6894533b709b
Content-Type: application/json

{
    "code": 2334
}

###

### Update a user by ID
PUT  http://localhost:3010/users/1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane.doe@example.com"
}

###

### Delete a user by ID
DELETE  http://localhost:3010/users/0194036f-65c8-72a0-bd95-b56b1989444a
Content-Type: application/json
###

### Get all users
GET http://localhost:3010/users
Content-Type: application/json

### Get all users with reports
GET http://localhost:3010/users/reports
Content-Type: application/json

### Start OAuth flow
GET http://localhost:3010/auth/google
Content-Type: application/json